name: Setup Captain
description: Installs the Captain CLI
author: RWX
branding:
  icon: navigation
  color: green
inputs:
  version:
    description: |
      Version of the Captain CLI to install.
      Must either be "v1", "v2", or a specific version.
      If not specified, "v2" is the default which will install the latest 2.x.x release.
    default: v2
    required: false
runs:
  using: 'node24'
  main: 'dist/index.js'
