name: Continuous Integration
on:
  push:
jobs:
  test_default_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./
      - run: captain --version | grep '^v2\.'

  test_specific_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./
        with:
          version: v0.8.0
      - run: captain --version | grep '^v0\.8\.0$'

  test_specific_version_without_v_prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./
        with:
          version: 1.0.57
      - run: captain --version | grep '^v1\.0\.57$'

  test_unstable_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./
        with:
          version: unstable
      - run: captain --version | grep '^unstable-'
