name: Continuous Delivery
run-name: Tag new release
on:
  workflow_run:
    workflows:
      - Continuous Integration
    branches:
      - v1
    types:
      - completed
jobs:
  push-tags:
    name: Push tags
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          version=$(cat version)
          majorMinor=$(echo $version | awk -F '.' '{print $1 "." $2}')

          git tag "v$version"
          git tag "v$majorMinor"
          git push --force --tags

          echo "newReleaseTag=v$version" >> $GITHUB_ENV
      - uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.newReleaseTag }}
          release_name: Release ${{ env.newReleaseTag }}
          draft: false
          prerelease: contains(env.newReleaseTag, "-")
